# 03 — Run experiments

Configure and launch experiments from a **single configuration cell** below.

Each run writes under the configured storage root (`outputs/runs/` locally, `UH_CV/runs/` on Google Drive).

**Prerequisite:** notebook 02 → `data/annotations/validation_lengths.csv`

In [1]:
from src.colab_bootstrap import setup_notebook_environment
from src.config import get_config
from src.experiments import load_validation_image_ids
from src.experiments.notebook_helpers import (
    RunExperimentsConfig,
    build_experiment_specs,
    preview_experiment_specs,
    project_config_for_experiments,
    resolve_runs_root,
    run_configured_experiments,
)
from src.utils import setup_logging

REPO, STORAGE = setup_notebook_environment(mount_drive=True)
setup_logging()
cfg = get_config()
print(f"Storage: {STORAGE} | Colab: {cfg.is_colab}")
VALIDATION_IDS = load_validation_image_ids(cfg)
print(f"Validation set: {len(VALIDATION_IDS)} images")

Storage: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv | Colab: False
2026-06-02 23:12:33 | INFO     | src.experiments | Loaded 30 validation image IDs from validation_lengths.csv
Validation set: 30 images

## Configuration

Edit this cell only. Set `RUN = True` to execute; leave `False` to preview the experiment grid without running.

Use `experiments=[...]` for explicit runs (legacy mode). Otherwise a grid is built from `pipelines` × `methods` × `splits`.

In [2]:
RUN = True  # set False to preview specs without executing

RUN_CFG = RunExperimentsConfig(
    # --- scope ---
    pipelines=["advanced"],           # "baseline" | "advanced"
    methods=["skeleton"],
    splits=["valid"],
    image_ids=None,                    # explicit list overrides validation_set_only
    validation_set_only=True,          # use all IDs from validation_lengths.csv
    limit=None,

    # --- execution ---
    overwrite=True,
    visualize=True,                   # save debug figures under run_dir/figures/
    evaluate=True,
    runs_root=None,                   # default: cfg.runs_root (Drive or outputs/runs)
    run_name_template="{pipeline}_{method}_grid_v1",

    # --- Colab / Drive persistence (all default True) ---
    cache_results=True,
    save_figures_to_drive=True,
    save_metrics_to_drive=True,
    save_predictions_to_drive=True,

    # --- advanced pipeline flags (when pipeline="advanced") ---
    perspective=False,
    use_grid_auto_calibration=True,
    use_depth_estimation=False,
    use_3d_measurement=False,

    # --- regression calibration (notebook 02 labels required) ---
    run_regression_calibration=False,   # True: train + evaluate sklearn length model
    regression_run_name="regression_calibrated_v1",
    regression_model_type="random_forest",  # or "xgboost" if installed
    regression_train_split="valid",

    # --- optional: explicit experiment list (overrides grid above) ---
    experiments=None,
    # experiments=[
    #     {"pipeline": "advanced", "method": "skeleton", "run_name": "advanced_full_v2",
    #      "split": "valid", "validation_set_only": True, "overwrite": True,
    #      "use_grid_auto_calibration": True, "use_depth_estimation": True,
    #      "use_3d_measurement": True},
    # ],
)

SPECS = build_experiment_specs(RUN_CFG)
preview_experiment_specs(SPECS, RUN_CFG)

,run_name,pipeline,method,split,visualize,perspective,grid,depth,3d
0,advanced_skeleton_grid_v1,advanced,skeleton,valid,True,False,True,False,False

## Run experiments

In [3]:
import pandas as pd

exp_cfg = project_config_for_experiments(RUN_CFG)
runs_root = resolve_runs_root(RUN_CFG)

if RUN:
    summary = run_configured_experiments(RUN_CFG, SPECS, cfg=exp_cfg)
else:
    print("RUN=False — skipped execution. Set RUN=True in the configuration cell.")
    summary = pd.DataFrame()

if len(summary):
    display(summary[[c for c in ["run_name", "pipeline", "method", "n_predictions", "mae_mm", "rmse_mm", "run_dir"] if c in summary.columns]])

2026-06-02 23:12:47 | INFO     | src.experiments | Running experiment 1/1: {'pipeline': 'advanced', 'method': 'skeleton', 'split': 'valid', 'run_name': 'advanced_skeleton_grid_v1', 'overwrite': True, 'visualize': True, 'evaluate': True, 'limit': None, 'validation_set_only': True, 'perspective': False, 'use_grid_auto_calibration': True, 'use_depth_estimation': False, 'use_3d_measurement': False}
2026-06-02 23:12:47 | INFO     | src.experiments | Loaded 30 validation image IDs from validation_lengths.csv
2026-06-02 23:12:47 | INFO     | src.experiments.run_manager | Saved run config: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/config.json
2026-06-02 23:12:47 | INFO     | src.pipelines.advanced | AdvancedPipeline: split=valid method=skeleton grid=True depth=False 3d=False perspective=False

Advanced (valid, n=30): 0img [00:00, ?img/s]

2026-06-02 23:12:47 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.46, spacing=60.00); markers should be used
2026-06-02 23:12:47 | INFO     | src.calibration.marker | Estimated scale: 5.5492 px/mm (n=2 markers, mean)
2026-06-02 23:12:47 | WARNING  | src.pipelines.advanced_inference | 10786: grid calibration failed; falling back to marker scale
2026-06-02 23:12:51 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:12:51 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.46, spacing=60.00); markers should be used
2026-06-02 23:12:51 | INFO     | src.calibration.marker | Estimated scale: 5.5492 px/mm (n=2 markers, mean)
2026-06-02 23:12:51 | WARNING  | src.pipelines.advanced_inference | 10786: grid calibration failed; falling back to marker scale
2026-06-02 23:13:10 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/10786_overview.png

Advanced (valid, n=30): 1img [00:22, 22.86s/img]

2026-06-02 23:13:10 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.48, spacing=88.00); markers should be used
2026-06-02 23:13:10 | INFO     | src.calibration.marker | Estimated scale: 2.5409 px/mm (n=4 markers, mean)
2026-06-02 23:13:10 | WARNING  | src.pipelines.advanced_inference | 11050: grid calibration failed; falling back to marker scale
2026-06-02 23:13:11 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:11 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.48, spacing=88.00); markers should be used
2026-06-02 23:13:11 | INFO     | src.calibration.marker | Estimated scale: 2.5409 px/mm (n=4 markers, mean)
2026-06-02 23:13:11 | WARNING  | src.pipelines.advanced_inference | 11050: grid calibration failed; falling back to marker scale
2026-06-02 23:13:16 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/11050_overview.png

Advanced (valid, n=30): 2img [00:29, 13.10s/img]

2026-06-02 23:13:16 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.44, spacing=24.00); markers should be used
2026-06-02 23:13:16 | INFO     | src.calibration.marker | Estimated scale: 1.8444 px/mm (n=4 markers, mean)
2026-06-02 23:13:16 | WARNING  | src.pipelines.advanced_inference | 12288: grid calibration failed; falling back to marker scale
2026-06-02 23:13:17 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:17 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.44, spacing=24.00); markers should be used
2026-06-02 23:13:17 | INFO     | src.calibration.marker | Estimated scale: 1.8444 px/mm (n=4 markers, mean)
2026-06-02 23:13:17 | WARNING  | src.pipelines.advanced_inference | 12288: grid calibration failed; falling back to marker scale
2026-06-02 23:13:19 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/12288_overview.png

Advanced (valid, n=30): 3img [00:31,  8.23s/img]

2026-06-02 23:13:19 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=24.00); markers should be used
2026-06-02 23:13:19 | INFO     | src.calibration.marker | Estimated scale: 2.5430 px/mm (n=3 markers, mean)
2026-06-02 23:13:19 | WARNING  | src.pipelines.advanced_inference | 12719: grid calibration failed; falling back to marker scale
2026-06-02 23:13:19 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:19 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=24.00); markers should be used
2026-06-02 23:13:19 | INFO     | src.calibration.marker | Estimated scale: 2.5430 px/mm (n=3 markers, mean)
2026-06-02 23:13:19 | WARNING  | src.pipelines.advanced_inference | 12719: grid calibration failed; falling back to marker scale
2026-06-02 23:13:21 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/12719_overview.png

Advanced (valid, n=30): 4img [00:33,  5.77s/img]

2026-06-02 23:13:21 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.45, spacing=24.00); markers should be used
2026-06-02 23:13:21 | INFO     | src.calibration.marker | Estimated scale: 1.8519 px/mm (n=4 markers, mean)
2026-06-02 23:13:21 | WARNING  | src.pipelines.advanced_inference | 12797: grid calibration failed; falling back to marker scale
2026-06-02 23:13:21 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:21 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.45, spacing=24.00); markers should be used
2026-06-02 23:13:21 | INFO     | src.calibration.marker | Estimated scale: 1.8519 px/mm (n=4 markers, mean)
2026-06-02 23:13:21 | WARNING  | src.pipelines.advanced_inference | 12797: grid calibration failed; falling back to marker scale
2026-06-02 23:13:23 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/12797_overview.png

Advanced (valid, n=30): 5img [00:36,  4.70s/img]

2026-06-02 23:13:24 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.53, spacing=60.00); markers should be used
2026-06-02 23:13:24 | INFO     | src.calibration.marker | Estimated scale: 4.1114 px/mm (n=4 markers, mean)
2026-06-02 23:13:24 | WARNING  | src.pipelines.advanced_inference | 13736: grid calibration failed; falling back to marker scale
2026-06-02 23:13:27 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:27 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.53, spacing=60.00); markers should be used
2026-06-02 23:13:27 | INFO     | src.calibration.marker | Estimated scale: 4.1114 px/mm (n=4 markers, mean)
2026-06-02 23:13:27 | WARNING  | src.pipelines.advanced_inference | 13736: grid calibration failed; falling back to marker scale
2026-06-02 23:13:43 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/13736_overview.png

Advanced (valid, n=30): 6img [00:55,  9.66s/img]

2026-06-02 23:13:43 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.49, spacing=60.00); markers should be used
2026-06-02 23:13:43 | INFO     | src.calibration.marker | Estimated scale: 4.7478 px/mm (n=4 markers, mean)
2026-06-02 23:13:43 | WARNING  | src.pipelines.advanced_inference | 14227: grid calibration failed; falling back to marker scale
2026-06-02 23:13:46 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:13:46 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.49, spacing=60.00); markers should be used
2026-06-02 23:13:46 | INFO     | src.calibration.marker | Estimated scale: 4.7478 px/mm (n=4 markers, mean)
2026-06-02 23:13:46 | WARNING  | src.pipelines.advanced_inference | 14227: grid calibration failed; falling back to marker scale
2026-06-02 23:14:00 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/14227_overview.png

Advanced (valid, n=30): 7img [01:12, 12.12s/img]

2026-06-02 23:14:00 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.42, spacing=127.83); markers should be used
2026-06-02 23:14:00 | INFO     | src.calibration.marker | Estimated scale: 9.0600 px/mm (n=1 markers, mean)
2026-06-02 23:14:00 | WARNING  | src.pipelines.advanced_inference | 1491: grid calibration failed; falling back to marker scale
2026-06-02 23:14:04 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:04 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.42, spacing=127.83); markers should be used
2026-06-02 23:14:04 | INFO     | src.calibration.marker | Estimated scale: 9.0600 px/mm (n=1 markers, mean)
2026-06-02 23:14:04 | WARNING  | src.pipelines.advanced_inference | 1491: grid calibration failed; falling back to marker scale
2026-06-02 23:14:22 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/1491_overview.png

Advanced (valid, n=30): 8img [01:34, 15.24s/img]

2026-06-02 23:14:22 | INFO     | src.calibration.grid_auto | Grid calibration: 33.13 px/square (3.3128 px/mm) conf=0.64 H=7 V=8
2026-06-02 23:14:22 | INFO     | src.calibration.marker | Estimated scale: 2.5209 px/mm (n=2 markers, mean)
2026-06-02 23:14:22 | WARNING  | src.pipelines.advanced_inference | 15157: grid ppm ratio 1.31 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:22 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:22 | INFO     | src.calibration.grid_auto | Grid calibration: 33.13 px/square (3.3128 px/mm) conf=0.64 H=7 V=8
2026-06-02 23:14:22 | INFO     | src.calibration.marker | Estimated scale: 2.5209 px/mm (n=2 markers, mean)
2026-06-02 23:14:22 | WARNING  | src.pipelines.advanced_inference | 15157: grid ppm ratio 1.31 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:24 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/15157_overview.png

Advanced (valid, n=30): 9img [01:37, 11.19s/img]

2026-06-02 23:14:24 | INFO     | src.calibration.grid_auto | Grid calibration: 24.00 px/square (2.4000 px/mm) conf=0.73 H=21 V=8
2026-06-02 23:14:24 | INFO     | src.calibration.marker | Estimated scale: 2.3469 px/mm (n=4 markers, mean)
2026-06-02 23:14:25 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:25 | INFO     | src.calibration.grid_auto | Grid calibration: 24.00 px/square (2.4000 px/mm) conf=0.73 H=21 V=8
2026-06-02 23:14:25 | INFO     | src.calibration.marker | Estimated scale: 2.3469 px/mm (n=4 markers, mean)
2026-06-02 23:14:27 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/15199_overview.png

Advanced (valid, n=30): 10img [01:39,  8.56s/img]

2026-06-02 23:14:27 | INFO     | src.calibration.grid_auto | Grid calibration: 24.95 px/square (2.4950 px/mm) conf=0.57 H=30 V=5
2026-06-02 23:14:27 | INFO     | src.calibration.marker | Estimated scale: 1.8429 px/mm (n=4 markers, mean)
2026-06-02 23:14:27 | WARNING  | src.pipelines.advanced_inference | 15660: grid ppm ratio 1.35 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:27 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:27 | INFO     | src.calibration.grid_auto | Grid calibration: 24.95 px/square (2.4950 px/mm) conf=0.57 H=30 V=5
2026-06-02 23:14:27 | INFO     | src.calibration.marker | Estimated scale: 1.8429 px/mm (n=4 markers, mean)
2026-06-02 23:14:27 | WARNING  | src.pipelines.advanced_inference | 15660: grid ppm ratio 1.35 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:29 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/15660_overview.png

Advanced (valid, n=30): 11img [01:42,  6.73s/img]

2026-06-02 23:14:29 | INFO     | src.calibration.grid_auto | Grid calibration: 25.53 px/square (2.5532 px/mm) conf=0.51 H=28 V=9
2026-06-02 23:14:29 | INFO     | src.calibration.marker | Estimated scale: 1.7178 px/mm (n=4 markers, mean)
2026-06-02 23:14:29 | WARNING  | src.pipelines.advanced_inference | 16307: grid ppm ratio 1.49 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:30 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:30 | INFO     | src.calibration.grid_auto | Grid calibration: 25.53 px/square (2.5532 px/mm) conf=0.51 H=28 V=9
2026-06-02 23:14:30 | INFO     | src.calibration.marker | Estimated scale: 1.7178 px/mm (n=4 markers, mean)
2026-06-02 23:14:30 | WARNING  | src.pipelines.advanced_inference | 16307: grid ppm ratio 1.49 outside [0.85, 1.15]; using marker scale
2026-06-02 23:14:32 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/16307_overview.png

Advanced (valid, n=30): 12img [01:44,  5.41s/img]

2026-06-02 23:14:32 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.43, spacing=69.17); markers should be used
2026-06-02 23:14:32 | INFO     | src.calibration.marker | Estimated scale: 4.0118 px/mm (n=4 markers, mean)
2026-06-02 23:14:32 | WARNING  | src.pipelines.advanced_inference | 21625: grid calibration failed; falling back to marker scale
2026-06-02 23:14:35 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:36 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.43, spacing=69.17); markers should be used
2026-06-02 23:14:36 | INFO     | src.calibration.marker | Estimated scale: 4.0118 px/mm (n=4 markers, mean)
2026-06-02 23:14:36 | WARNING  | src.pipelines.advanced_inference | 21625: grid calibration failed; falling back to marker scale
2026-06-02 23:14:53 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/21625_overview.png

Advanced (valid, n=30): 13img [02:05, 10.15s/img]

2026-06-02 23:14:53 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.48, spacing=69.12); markers should be used
2026-06-02 23:14:53 | INFO     | src.calibration.marker | Estimated scale: 5.3950 px/mm (n=4 markers, mean)
2026-06-02 23:14:53 | WARNING  | src.pipelines.advanced_inference | 21722: grid calibration failed; falling back to marker scale
2026-06-02 23:14:58 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:14:58 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.48, spacing=69.12); markers should be used
2026-06-02 23:14:58 | INFO     | src.calibration.marker | Estimated scale: 5.3950 px/mm (n=4 markers, mean)
2026-06-02 23:14:58 | WARNING  | src.pipelines.advanced_inference | 21722: grid calibration failed; falling back to marker scale
2026-06-02 23:15:24 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/21722_overview.png

Advanced (valid, n=30): 14img [02:36, 16.36s/img]

2026-06-02 23:15:24 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.46, spacing=525.60); markers should be used
2026-06-02 23:15:24 | INFO     | src.calibration.marker | Estimated scale: 5.2814 px/mm (n=2 markers, mean)
2026-06-02 23:15:24 | WARNING  | src.pipelines.advanced_inference | 22075: grid calibration failed; falling back to marker scale
2026-06-02 23:15:28 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:15:28 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.46, spacing=525.60); markers should be used
2026-06-02 23:15:28 | INFO     | src.calibration.marker | Estimated scale: 5.2814 px/mm (n=2 markers, mean)
2026-06-02 23:15:28 | WARNING  | src.pipelines.advanced_inference | 22075: grid calibration failed; falling back to marker scale
2026-06-02 23:15:47 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/22075_overview.png

Advanced (valid, n=30): 15img [02:59, 18.52s/img]

2026-06-02 23:15:47 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.49, spacing=69.12); markers should be used
2026-06-02 23:15:47 | INFO     | src.calibration.marker | Estimated scale: 1.7800 px/mm (n=1 markers, mean)
2026-06-02 23:15:47 | WARNING  | src.pipelines.advanced_inference | 2572: grid calibration failed; falling back to marker scale
2026-06-02 23:15:57 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:15:58 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.49, spacing=69.12); markers should be used
2026-06-02 23:15:58 | INFO     | src.calibration.marker | Estimated scale: 1.7800 px/mm (n=1 markers, mean)
2026-06-02 23:15:58 | WARNING  | src.pipelines.advanced_inference | 2572: grid calibration failed; falling back to marker scale
2026-06-02 23:16:43 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/2572_overview.png

Advanced (valid, n=30): 16img [03:55, 29.68s/img]

2026-06-02 23:16:43 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.47, spacing=60.00); markers should be used
2026-06-02 23:16:43 | INFO     | src.calibration.marker | Estimated scale: 4.3883 px/mm (n=4 markers, mean)
2026-06-02 23:16:43 | WARNING  | src.pipelines.advanced_inference | 3257: grid calibration failed; falling back to marker scale
2026-06-02 23:16:46 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:16:46 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.47, spacing=60.00); markers should be used
2026-06-02 23:16:46 | INFO     | src.calibration.marker | Estimated scale: 4.3883 px/mm (n=4 markers, mean)
2026-06-02 23:16:46 | WARNING  | src.pipelines.advanced_inference | 3257: grid calibration failed; falling back to marker scale
2026-06-02 23:17:02 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/3257_overview.png

Advanced (valid, n=30): 17img [04:14, 26.43s/img]

2026-06-02 23:17:02 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.51, spacing=60.00); markers should be used
2026-06-02 23:17:02 | INFO     | src.calibration.marker | Estimated scale: 3.9114 px/mm (n=4 markers, mean)
2026-06-02 23:17:02 | WARNING  | src.pipelines.advanced_inference | 3270: grid calibration failed; falling back to marker scale
2026-06-02 23:17:05 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:17:06 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.51, spacing=60.00); markers should be used
2026-06-02 23:17:06 | INFO     | src.calibration.marker | Estimated scale: 3.9114 px/mm (n=4 markers, mean)
2026-06-02 23:17:06 | WARNING  | src.pipelines.advanced_inference | 3270: grid calibration failed; falling back to marker scale
2026-06-02 23:17:24 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/3270_overview.png

Advanced (valid, n=30): 18img [04:36, 25.11s/img]

2026-06-02 23:17:24 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.43, spacing=54.40); markers should be used
2026-06-02 23:17:24 | INFO     | src.calibration.marker | Estimated scale: 2.6729 px/mm (n=4 markers, mean)
2026-06-02 23:17:24 | WARNING  | src.pipelines.advanced_inference | 36185: grid calibration failed; falling back to marker scale
2026-06-02 23:17:26 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:17:26 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.43, spacing=54.40); markers should be used
2026-06-02 23:17:26 | INFO     | src.calibration.marker | Estimated scale: 2.6729 px/mm (n=4 markers, mean)
2026-06-02 23:17:26 | WARNING  | src.pipelines.advanced_inference | 36185: grid calibration failed; falling back to marker scale
2026-06-02 23:17:35 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/36185_overview.png

Advanced (valid, n=30): 19img [04:48, 21.09s/img]

2026-06-02 23:17:35 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.56, spacing=60.00); markers should be used
2026-06-02 23:17:35 | INFO     | src.calibration.marker | Estimated scale: 4.9949 px/mm (n=3 markers, mean)
2026-06-02 23:17:35 | WARNING  | src.pipelines.advanced_inference | 37856: grid calibration failed; falling back to marker scale
2026-06-02 23:17:38 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:17:38 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.56, spacing=60.00); markers should be used
2026-06-02 23:17:38 | INFO     | src.calibration.marker | Estimated scale: 4.9949 px/mm (n=3 markers, mean)
2026-06-02 23:17:38 | WARNING  | src.pipelines.advanced_inference | 37856: grid calibration failed; falling back to marker scale
2026-06-02 23:17:51 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/37856_overview.png

Advanced (valid, n=30): 20img [05:03, 19.48s/img]

2026-06-02 23:17:51 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=60.00); markers should be used
2026-06-02 23:17:51 | INFO     | src.calibration.marker | Estimated scale: 3.1570 px/mm (n=2 markers, mean)
2026-06-02 23:17:51 | WARNING  | src.pipelines.advanced_inference | 4288: grid calibration failed; falling back to marker scale
2026-06-02 23:17:53 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:17:53 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=60.00); markers should be used
2026-06-02 23:17:53 | INFO     | src.calibration.marker | Estimated scale: 3.1570 px/mm (n=2 markers, mean)
2026-06-02 23:17:53 | WARNING  | src.pipelines.advanced_inference | 4288: grid calibration failed; falling back to marker scale
2026-06-02 23:18:02 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/4288_overview.png

Advanced (valid, n=30): 21img [05:15, 17.07s/img]

2026-06-02 23:18:03 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.39, spacing=75.13); markers should be used
2026-06-02 23:18:03 | INFO     | src.calibration.marker | Estimated scale: 3.2618 px/mm (n=4 markers, mean)
2026-06-02 23:18:03 | WARNING  | src.pipelines.advanced_inference | 5055: grid calibration failed; falling back to marker scale
2026-06-02 23:18:04 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:18:04 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.39, spacing=75.13); markers should be used
2026-06-02 23:18:04 | INFO     | src.calibration.marker | Estimated scale: 3.2618 px/mm (n=4 markers, mean)
2026-06-02 23:18:04 | WARNING  | src.pipelines.advanced_inference | 5055: grid calibration failed; falling back to marker scale
2026-06-02 23:18:13 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/5055_overview.png

Advanced (valid, n=30): 22img [05:25, 14.97s/img]

2026-06-02 23:18:13 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=540.00); markers should be used
2026-06-02 23:18:13 | INFO     | src.calibration.marker | Estimated scale: 2.8039 px/mm (n=4 markers, mean)
2026-06-02 23:18:13 | WARNING  | src.pipelines.advanced_inference | 643: grid calibration failed; falling back to marker scale
2026-06-02 23:18:14 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:18:14 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=540.00); markers should be used
2026-06-02 23:18:14 | INFO     | src.calibration.marker | Estimated scale: 2.8039 px/mm (n=4 markers, mean)
2026-06-02 23:18:14 | WARNING  | src.pipelines.advanced_inference | 643: grid calibration failed; falling back to marker scale
2026-06-02 23:18:23 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/643_overview.png

Advanced (valid, n=30): 23img [05:36, 13.69s/img]

2026-06-02 23:18:23 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.42, spacing=137.03); markers should be used
2026-06-02 23:18:23 | INFO     | src.calibration.marker | Estimated scale: 5.6644 px/mm (n=2 markers, mean)
2026-06-02 23:18:23 | WARNING  | src.pipelines.advanced_inference | 8028: grid calibration failed; falling back to marker scale
2026-06-02 23:18:27 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:18:27 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.42, spacing=137.03); markers should be used
2026-06-02 23:18:27 | INFO     | src.calibration.marker | Estimated scale: 5.6644 px/mm (n=2 markers, mean)
2026-06-02 23:18:27 | WARNING  | src.pipelines.advanced_inference | 8028: grid calibration failed; falling back to marker scale
2026-06-02 23:18:43 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/8028_overview.png

Advanced (valid, n=30): 24img [05:56, 15.65s/img]

2026-06-02 23:18:44 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.38, spacing=91.59); markers should be used
2026-06-02 23:18:44 | INFO     | src.calibration.marker | Estimated scale: 5.6465 px/mm (n=2 markers, mean)
2026-06-02 23:18:44 | WARNING  | src.pipelines.advanced_inference | 8146: grid calibration failed; falling back to marker scale
2026-06-02 23:18:48 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:18:48 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.38, spacing=91.59); markers should be used
2026-06-02 23:18:48 | INFO     | src.calibration.marker | Estimated scale: 5.6465 px/mm (n=2 markers, mean)
2026-06-02 23:18:48 | WARNING  | src.pipelines.advanced_inference | 8146: grid calibration failed; falling back to marker scale
2026-06-02 23:19:06 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/8146_overview.png

Advanced (valid, n=30): 25img [06:19, 17.82s/img]

2026-06-02 23:19:06 | INFO     | src.calibration.grid_auto | Grid calibration: 60.00 px/square (6.0000 px/mm) conf=0.79 H=35 V=22
2026-06-02 23:19:06 | INFO     | src.calibration.marker | Estimated scale: 2.6143 px/mm (n=4 markers, mean)
2026-06-02 23:19:06 | WARNING  | src.pipelines.advanced_inference | 8293: grid ppm ratio 2.30 outside [0.85, 1.15]; using marker scale
2026-06-02 23:19:08 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:08 | INFO     | src.calibration.grid_auto | Grid calibration: 60.00 px/square (6.0000 px/mm) conf=0.79 H=35 V=22
2026-06-02 23:19:08 | INFO     | src.calibration.marker | Estimated scale: 2.6143 px/mm (n=4 markers, mean)
2026-06-02 23:19:08 | WARNING  | src.pipelines.advanced_inference | 8293: grid ppm ratio 2.30 outside [0.85, 1.15]; using marker scale
2026-06-02 23:19:18 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/8293_overview.png

Advanced (valid, n=30): 26img [06:30, 15.85s/img]

2026-06-02 23:19:18 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=60.00); markers should be used
2026-06-02 23:19:18 | INFO     | src.calibration.marker | Estimated scale: 2.7624 px/mm (n=4 markers, mean)
2026-06-02 23:19:18 | WARNING  | src.pipelines.advanced_inference | 8309: grid calibration failed; falling back to marker scale
2026-06-02 23:19:20 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:20 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.50, spacing=60.00); markers should be used
2026-06-02 23:19:20 | INFO     | src.calibration.marker | Estimated scale: 2.7624 px/mm (n=4 markers, mean)
2026-06-02 23:19:20 | WARNING  | src.pipelines.advanced_inference | 8309: grid calibration failed; falling back to marker scale
2026-06-02 23:19:31 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/8309_overview.png

Advanced (valid, n=30): 27img [06:43, 14.99s/img]

2026-06-02 23:19:31 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.41, spacing=42.48); markers should be used
2026-06-02 23:19:31 | INFO     | src.calibration.marker | Estimated scale: 2.3212 px/mm (n=4 markers, mean)
2026-06-02 23:19:31 | WARNING  | src.pipelines.advanced_inference | 8998: grid calibration failed; falling back to marker scale
2026-06-02 23:19:31 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:31 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.41, spacing=42.48); markers should be used
2026-06-02 23:19:31 | INFO     | src.calibration.marker | Estimated scale: 2.3212 px/mm (n=4 markers, mean)
2026-06-02 23:19:31 | WARNING  | src.pipelines.advanced_inference | 8998: grid calibration failed; falling back to marker scale
2026-06-02 23:19:33 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/8998_overview.png

Advanced (valid, n=30): 28img [06:46, 11.32s/img]

2026-06-02 23:19:33 | INFO     | src.calibration.grid_auto | Grid calibration: 28.80 px/square (2.8800 px/mm) conf=0.75 H=17 V=8
2026-06-02 23:19:33 | INFO     | src.calibration.marker | Estimated scale: 2.3078 px/mm (n=4 markers, mean)
2026-06-02 23:19:33 | WARNING  | src.pipelines.advanced_inference | 9315: grid ppm ratio 1.25 outside [0.85, 1.15]; using marker scale
2026-06-02 23:19:34 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:34 | INFO     | src.calibration.grid_auto | Grid calibration: 28.80 px/square (2.8800 px/mm) conf=0.75 H=17 V=8
2026-06-02 23:19:34 | INFO     | src.calibration.marker | Estimated scale: 2.3078 px/mm (n=4 markers, mean)
2026-06-02 23:19:34 | WARNING  | src.pipelines.advanced_inference | 9315: grid ppm ratio 1.25 outside [0.85, 1.15]; using marker scale
2026-06-02 23:19:35 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/9315_overview.png

Advanced (valid, n=30): 29img [06:48,  8.51s/img]

2026-06-02 23:19:35 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.47, spacing=24.00); markers should be used
2026-06-02 23:19:35 | INFO     | src.calibration.marker | Estimated scale: 1.5060 px/mm (n=4 markers, mean)
2026-06-02 23:19:35 | WARNING  | src.pipelines.advanced_inference | 9701: grid calibration failed; falling back to marker scale
2026-06-02 23:19:36 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:36 | WARNING  | src.calibration.grid_auto | Grid calibration unreliable (conf=0.47, spacing=24.00); markers should be used
2026-06-02 23:19:36 | INFO     | src.calibration.marker | Estimated scale: 1.5060 px/mm (n=4 markers, mean)
2026-06-02 23:19:36 | WARNING  | src.pipelines.advanced_inference | 9701: grid calibration failed; falling back to marker scale
2026-06-02 23:19:37 | INFO     | src.visualization._common | Saved figure: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/figures/9701_overview.png

Advanced (valid, n=30): 30img [06:50, 13.68s/img]

2026-06-02 23:19:37 | INFO     | src.pipelines.advanced_inference | Wrote 30 advanced predictions to /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/predictions.csv
2026-06-02 23:19:37 | INFO     | src.evaluation | Loaded 30 ground-truth rows from /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/data/annotations/validation_lengths.csv
2026-06-02 23:19:37 | INFO     | src.evaluation | Metrics (n=30): MAE=51.651 mm, RMSE=125.717 mm
2026-06-02 23:19:37 | INFO     | src.evaluation | Wrote comparison table to /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/comparison.csv
2026-06-02 23:19:37 | INFO     | src.evaluation | Wrote metrics to /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/advanced_skeleton_grid_v1/metrics.json
2026-06-02 23:19:37 | INFO     | src.evaluation | Logged experiment to /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/metrics/experiments.jsonl
2026-06-02 23:19:37 | INFO     | src.experiments.run_manager | Appended run to registry: /Users/sebastianinouye/Desktop/Everything/Projects/Github/fishnet_cv/outputs/runs/experiments.csv

,run_name,pipeline,method,n_predictions,mae_mm,rmse_mm,run_dir
0,advanced_skeleton_grid_v1,advanced,skeleton,30,51.651321,125.716694,/Users/sebastianinouye/Desktop/Everything/Proj...

## Sanity check

Confirms every annotated fish was predicted and evaluated when using the validation set.

In [4]:
if len(summary) and RUN_CFG.validation_set_only and RUN_CFG.image_ids is None:
    n_gt = len(VALIDATION_IDS)
    for _, row in summary.iterrows():
        pred_path = Path(row["predictions_path"])
        comp_path = Path(row["comparison_path"]) if pd.notna(row.get("comparison_path")) else None
        pred = pd.read_csv(pred_path)
        comp = pd.read_csv(comp_path) if comp_path and comp_path.is_file() else None
        print(f"{row['run_name']}: predictions={len(pred)}", end="")
        if comp is not None:
            print(f"  evaluated={len(comp)}", end="")
            assert len(pred) == n_gt, f"{row['run_name']}: not all validation IDs predicted"
            assert len(comp) == n_gt, f"{row['run_name']}: evaluation incomplete"
            print("  OK")
        else:
            print("  (no comparison.csv)")
else:
    print("Skipped — custom image_ids or no runs executed.")

NameError: name 'Path' is not defined